-- MySQL Script generated by MySQL Workbench
-- seg 15 fev 2021 15:02:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gerenciamentoUsuario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciamentoUsuario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciamentoUsuario` DEFAULT CHARACTER SET utf8 ;
USE `gerenciamentoUsuario` ;

-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`cargo` (
  `carNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`carNome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`usuario` (
  `usuCpf` VARCHAR(11) NOT NULL,
  `usuNome` VARCHAR(45) NOT NULL,
  `usuSexo` CHAR NULL,
  `usuDateNasc` DATE NULL,
  `usu_carNome` VARCHAR(45) NOT NULL,
  `usuDataCadastro` DATE NOT NULL,
  PRIMARY KEY (`usuCpf`),
  INDEX `fk_usuario_cargo_idx` (`usu_carNome` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cargo`
    FOREIGN KEY (`usu_carNome`)
    REFERENCES `gerenciamentoUsuario`.`cargo` (`carNome`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`perfil` (
  `perNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`perNome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`usuario_perfil` (
  `usp_usuCpf` VARCHAR(11) NOT NULL,
  `usp_perNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usp_usuCpf`, `usp_perNome`),
  INDEX `fk_usuario_has_perfil_perfil1_idx` (`usp_perNome` ASC) VISIBLE,
  INDEX `fk_usuario_has_perfil_usuario1_idx` (`usp_usuCpf` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_perfil_usuario1`
    FOREIGN KEY (`usp_usuCpf`)
    REFERENCES `gerenciamentoUsuario`.`usuario` (`usuCpf`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_has_perfil_perfil1`
    FOREIGN KEY (`usp_perNome`)
    REFERENCES `gerenciamentoUsuario`.`perfil` (`perNome`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Planejador');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Comunicador');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Executor');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Analista');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Procrastinador');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Explosivo');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Competitivo');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Analítico');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Controlador');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Criativo');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Relacionamento');
INSERT INTO `gerenciamentoUsuario`.`perfil` (`perNome`) VALUES ('Comprometido');

INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Gerente de Tecnologia da Informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Analista de Tecnologia da Informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Assistente de Tecnologia da Informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Diretor de Tecnologia da Informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Supervisor de Tecnologia');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Coordenador de Tecnologia da Informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Trainee na área de Tecnologia da Informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Consultor de Tecnologia da informação');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Engenheiro de Software');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Engenheiro de Dados');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Gerente técnico');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Gerente de Produto/Software');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Gerente de segurança de Computação/rede/TI');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Engenheiro de Dados Sênior');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Engenheiro de Software Sênior');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Vice-presidente de TI');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Desenvolvedor Júnior');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Desenvolvedor Pleno');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Desenvolvedor Sênior');
INSERT INTO `gerenciamentoUsuario`.`cargo` (`carNome`) VALUES ('Estagiário');


