-- MySQL Script generated by MySQL Workbench
-- sex 12 fev 2021 02:31:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gerenciamentoUsuario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciamentoUsuario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciamentoUsuario` DEFAULT CHARACTER SET utf8 ;
USE `gerenciamentoUsuario` ;

-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`cargo` (
  `carNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`carNome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`usuario` (
  `usuCpf` VARCHAR(11) NOT NULL,
  `usuNome` VARCHAR(45) NOT NULL,
  `usuSexo` CHAR NULL,
  `usuDateNasc` DATE NULL,
  `usu_carNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuCpf`),
  INDEX `fk_usuario_cargo_idx` (`usu_carNome` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cargo`
    FOREIGN KEY (`usu_carNome`)
    REFERENCES `gerenciamentoUsuario`.`cargo` (`carNome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`perfil` (
  `perNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`perNome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentoUsuario`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentoUsuario`.`usuario_perfil` (
  `usp_usuCpf` VARCHAR(11) NOT NULL,
  `usp_perNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usp_usuCpf`, `usp_perNome`),
  INDEX `fk_usuario_has_perfil_perfil1_idx` (`usp_perNome` ASC) VISIBLE,
  INDEX `fk_usuario_has_perfil_usuario1_idx` (`usp_usuCpf` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_perfil_usuario1`
    FOREIGN KEY (`usp_usuCpf`)
    REFERENCES `gerenciamentoUsuario`.`usuario` (`usuCpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_perfil_perfil1`
    FOREIGN KEY (`usp_perNome`)
    REFERENCES `gerenciamentoUsuario`.`perfil` (`perNome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
