/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentousuario.view;

import gerenciamentousuario.controller.CargoController;
import gerenciamentousuario.controller.PerfilController;
import gerenciamentousuario.controller.UsuarioController;
import gerenciamentousuario.controller.UsuarioPerfilController;
import gerenciamentousuario.model.Cargo;
import gerenciamentousuario.model.Perfil;
import gerenciamentousuario.model.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 * Tela de cadastrar usuário e vincular os perfis a eles.
 * @author pedro-menezes
 */
public class CadastrarUsuario extends JFrame {
    private Inicio origem;
    /**
     * Construtor que recebe janela de inicio para executar funções.
     * @param origem - Inicio - janela inicial.
     */
    public CadastrarUsuario(Inicio origem) throws ParseException {
        initComponents();
        this.origem = origem;
        this.setVisible(true);
        addRadio();
        preencherCombo();
        preencherTabela();
        addMask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        labelCpf = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelNasc = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        radioM = new javax.swing.JRadioButton();
        radioF = new javax.swing.JRadioButton();
        comboCargo = new javax.swing.JComboBox<>();
        buttonCancelar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPerfis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textCpf = new javax.swing.JFormattedTextField();
        textNasc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuário");
        setResizable(false);

        labelCpf.setText("CPF:");

        labelNome.setText("Nome:");

        labelSexo.setText("Sexo:");

        labelCargo.setText("Cargo:");

        labelNasc.setText("Data de Nascimento:");

        radioM.setText("Masculino");

        radioF.setText("Feminino");

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitulo.setText("Cadastrar Usuário");

        tabelaPerfis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Perfil", "Adicionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPerfis);

        jLabel1.setText("Adicionar Perfis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSexo)
                                .addGap(18, 18, 18)
                                .addComponent(radioM)
                                .addGap(18, 18, 18)
                                .addComponent(radioF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome)
                                    .addComponent(labelCpf))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(labelCargo)
                            .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCpf)
                            .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSexo)
                            .addComponent(radioM)
                            .addComponent(radioF))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNasc)
                            .addComponent(textNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(labelCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que realiza o cadastro no sistema após o botão cadastrar ser apertado.
     * @param evt - ActionEvent - evento de click recebido pelo sistema.
     */
    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        try {
            Usuario usuario = new Usuario(getCpf(), textNome.getText(), new java.sql.Date(converteData(textNasc.getText()).getTime()), radioSelecionado(),  new java.sql.Date(System.currentTimeMillis()));
            new UsuarioController().adiciona(usuario, new Cargo(comboCargo.getSelectedItem().toString()));
            addPerfis(usuario);
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso", "Cadastro de Usuário", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            origem.atualizarTabela();
            origem.setEnabled(true);
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no cadastro",  "Cadastro de Usuário", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(CadastrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonCadastrarActionPerformed
    /**
     * Método referente ao botão cancelar, que após apertado fecha a janela.
     * @param evt - ActionEvent - evento de click recebido pelo sistema.
     */
    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelNasc;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton radioF;
    private javax.swing.JRadioButton radioM;
    private javax.swing.JTable tabelaPerfis;
    private javax.swing.JFormattedTextField textCpf;
    private javax.swing.JFormattedTextField textNasc;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que verifica qual radioButton está selecionado e retorna o sexo.
     * @return char - sexo seleciona 'M' ou 'F'.
     */
    private char radioSelecionado() {
        if (radioF.isSelected()) {
            return 'F';
        } else {
            return 'M';
        }
    }

    /**
     * Método que recebe data no formato normal e retorna no formato para o banco de dados.
     * @param texto - String - data no formato padrão.
     * @return Date - data convertida para formato do sql.
     * @throws ParseException tratamento de erro.
     */
    private Date converteData(String texto) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date aux = sdf.parse(texto);
        sdf.applyPattern("yyyy/MM/dd");
        String r = sdf.format(aux);
        return sdf.parse(r);
    }

    /**
     * Método que adiciona os dosi radioButtons em um grupo.
     */
    private void addRadio() {
        buttonGroup.add(radioF);
        buttonGroup.add(radioM);
    }
    
    /**
     * Método que preenche comboBox com cargos.
     */
    private void preencherCombo() {
        for (Cargo cargo : new CargoController().lista()) {
            comboCargo.addItem(cargo.getNome());
        }
    }

    /**
     * Método que preenche a tabela de perfis para serem adicionados ao usuário.
     */
    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPerfis.getModel();
        modelo.setNumRows(0);

        for (Perfil perfil : new PerfilController().lista()) {
            modelo.addRow(new Object[]{
                perfil.getNome()
            });
        }
    }
    
    /**@Override
     * Método que adiciona os perfis marcados ao usuário criado.
     * @param usuario Usuario - usuário que deve ser adicionado os perfis.
     */
    private void addPerfis(Usuario usuario) {
        ArrayList<String> nomesPerfis = new ArrayList<>();
        int linhas = tabelaPerfis.getRowCount();

        for (int i = 0; i < linhas; i++) {
            if (((Boolean) tabelaPerfis.getValueAt(i, 1)) != null) {
                nomesPerfis.add(String.valueOf(tabelaPerfis.getValueAt(i, 0)));
            }
        }

        UsuarioPerfilController usuPerController = new UsuarioPerfilController();
        for (String nomePerfil : nomesPerfis) {
                usuPerController.adiciona(new PerfilController().busca(nomePerfil), usuario);
        }
    }

    /**
     * Método para adicionar máscara de data e CPF as entradas de texto.
     * @throws ParseException tratamento de erro.
     */
    private void addMask() throws ParseException {
        MaskFormatter CPFMask = new MaskFormatter("###.###.###-##");
        MaskFormatter dataMask = new MaskFormatter("##/##/####");
        CPFMask.setValidCharacters("0123456789");
        dataMask.setValidCharacters("0123456789");

        textCpf.setValue(null);
        textCpf.setFormatterFactory(new DefaultFormatterFactory(CPFMask));
        textNasc.setValue(null);
        textNasc.setFormatterFactory(new DefaultFormatterFactory(dataMask));
    }

    /**
     * Método que retira as pontuações do CPF.
     * @return String - CPF formatado apenas com números.
     */
    private String getCpf() {
        String cpf = textCpf.getText().replace(".", "");
        cpf = cpf.replace("-", "");
        return cpf;
    }
}
