/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentousuario.view;

import gerenciamentousuario.controller.CargoController;
import gerenciamentousuario.controller.PerfilController;
import gerenciamentousuario.controller.UsuarioController;
import gerenciamentousuario.controller.UsuarioPerfilController;
import gerenciamentousuario.model.Cargo;
import gerenciamentousuario.model.Perfil;
import gerenciamentousuario.model.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro-menezes
 */
public class Inicio extends JFrame {

    /**
     * Creates new form index
     */
    public Inicio() throws ParseException {
        initComponents();
        atualizarTabela();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        buttonNovo = new javax.swing.JButton();
        panelTabela = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        buttonCadastro = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();
        radioAlfabetica = new javax.swing.JRadioButton();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Usuário");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setResizable(false);

        panelPrincipal.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));

        buttonNovo.setText("Editar");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        panelTabela.setViewportView(tabelaUsuario);

        buttonCadastro.setText("Novo");
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar(evt);
            }
        });

        comboTipo.setBackground(java.awt.SystemColor.controlLtHighlight);
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Cargo", "Perfil" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        radioAlfabetica.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        radioAlfabetica.setText("Ordem Alfabética");
        radioAlfabetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlfabeticaActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Gerenciamento de Usuários");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTabela)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(buttonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 674, Short.MAX_VALUE)
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAlfabetica)))
                .addContainerGap())
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAlfabetica))
                .addGap(9, 9, 9)
                .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonCadastro))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        String selecionado = comboTipo.getSelectedItem().toString();
        if (selecionado.equals("Usuário")) {
            new EditarUsuario(this);
        }
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void jButtonCadastrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar
        try {
            String selecionado = comboTipo.getSelectedItem().toString();
            if (selecionado.equals("Usuário")) {
                new CadastrarUsuario(this);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastrar

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        try {
            atualizarTabela();
        } catch (ParseException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    private void radioAlfabeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlfabeticaActionPerformed
        
    }//GEN-LAST:event_radioAlfabeticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane panelTabela;
    private javax.swing.JRadioButton radioAlfabetica;
    private javax.swing.JTable tabelaUsuario;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabela() throws ParseException {
        DefaultTableModel modelo = new DefaultTableModel();

        String selecionado = comboTipo.getSelectedItem().toString();

        switch (selecionado) {
            case "Usuário": {
                modelo.addColumn("CPF");
                modelo.addColumn("Nome");
                modelo.addColumn("Data de Nascimento");
                modelo.addColumn("Sexo");
                modelo.addColumn("Cargo");
                modelo.addColumn("Perfis");
                for (Usuario usuario : new UsuarioController().lista()) {
                    new UsuarioPerfilController().buscaPerfis(usuario);
                    modelo.addRow(new Object[]{
                        usuario.getCpf(),
                        usuario.getNome(),
                        converteData(usuario.getDataNascimento().toString()),
                        usuario.getSexo(),
                        usuario.getCargo().getNome(),
                        usuario.retornaTextoPerfis()
                    });
                }
                break;
            }
            case "Perfil": {
                modelo.addColumn("Nome");
                for (Perfil perfil : new PerfilController().lista()) {
                    modelo.addRow(new Object[]{
                        perfil.getNome()
                    });
                }
                break;
            }
            case "Cargo": {
                modelo.addColumn("Nome");
                modelo.setColumnCount(1);
                for (Cargo cargo : new CargoController().lista()) {
                    modelo.addRow(new Object[]{
                        cargo.getNome()
                    });
                }
            }
        }
        tabelaUsuario.setModel(modelo);
        tabelaUsuario.setEnabled(false);
    }
    
    private String converteData(String texto) throws ParseException{
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date aux = sdf.parse(texto);
        sdf.applyPattern("dd/MM/yyyy");
        String r = sdf.format(aux);
        return r;
    }
}
